safe: true
source: .
lsi: false
exclude: ['vendor']
markdown: rdiscount
pygments: true
permalink: /posts/:year/:month/:day/:title
rdiscount:
  extensions: [smart]

name: Leonardo Garcia Crespo
fname: Leo
lname: Garcia Crespo
url: http://leoasis.github.com
description: Badass Literally Obfuscated Guy
twitter: leogcrespo
github: leoasis
gravatar_url: http://gravatar.com/avatar/2d4686084d18b4991674f0cd4fbc6c58

comments:
  disqus:
    short_name: leogcrespo

analytics:
  google:
    tracking_id: UA-37579559-1
