source: .
plugins_dir: ./_plugins
lsi: false
exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']

gems:
  - jekyll-assets

permalink: /posts/:year/:month/:day/:title

name: Leonardo Garcia Crespo
fname: Leo
lname: Garcia Crespo
url: https://leoasis.github.io
description: Sharing my thoughts to the world
github_url: https://github.com/leoasis
repository: leoasis/leoasis.github.com
twitter: leogcrespo
gravatar_url: https://gravatar.com/avatar/2d4686084d18b4991674f0cd4fbc6c58

assets:
  cdn: ""
  skip_baseurl_with_cdn: true

analytics:
  google:
    tracking_id: UA-37579559-1
