source: .
plugins_dir: ./_plugins
lsi: false
exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']

gems:
  - jekyll-assets

permalink: /posts/:year/:month/:day/:title

name: Leonardo Garcia Crespo
fname: Leo
lname: Garcia Crespo
url: http://leoasis.github.com
description: Sharing my thoughts to the world
github_url: https://github.com/leoasis
twitter: leogcrespo
gravatar_url: http://gravatar.com/avatar/2d4686084d18b4991674f0cd4fbc6c58

comments:
  disqus:
    short_name: leogcrespo

analytics:
  google:
    tracking_id: UA-37579559-1
